### ISSUE TITLE
Upload doesn't complete

### ISSUE THREAD

**Issue by jammersonf** [OneOffTech/laravel-tus-upload#11]
I always receive error on postFinish
![image](https://user-images.githubusercontent.com/2231447/55295037-3562f180-53df-11e9-9dbb-0565255254ab.png)

I've tried with and without hooks
![image](https://user-images.githubusercontent.com/2231447/55295047-4a3f8500-53df-11e9-92be-845344f33808.png)

**Comment by avvertix** [comment]
From the second log, the metadata seems to show a complete upload. Have you tried to open the file or calculate the sha256 of the file and verify the uploaded file?

> I've tried with and without hooks

I would exclude a problem in the hooks, but with the hooks active have you checked che Laravel log and or the permissions of the hook files?

Just for double checking could you try to run the tusd binary directly and let Javascript connect to it directly?

For example 

```
vendor\oneofftech\laravel-tus-upload\bin\tusd-win.exe
```
Then check eventual errors in the Javascript console of the browser.

If I remember correctly it should listen on port 1080 and accept files on the `/files/` path, cross origin should be handled by tusd.

**Comment by avvertix** [comment]
I also found traces of a similar problem in one of the instances we used to test the upload via TUS. I'm investigating the problem.

@jammersonf if you have new insights please let me know

**Comment by avvertix** [comment]
@jammersonf are you using Windows, MacOS or Linux?

**Comment by avvertix** [comment]
The issue is stale and the problem cannot be replicated with the latest version. Closing here.
