### ISSUE TITLE
tus:start tusd-mac permission denied

### ISSUE THREAD

**Issue by s1rc** [OneOffTech/laravel-tus-upload#4]
I'm trying to start the Tus.io server with `php artisan tus:start` however I'm getting the following error:

```
ERROR output -----------------
sh: /Users/Matt/Development/PHP/test/bin/tusd-mac: Permission denied
sh: line 0: exec: /Users/Matt/Development/PHP/test/bin/tusd-mac: cannot execute: Undefined error: 0
```

I tried to set the executable and hooks dirs in tusupload.php to the vendor folder version, it also has the same error.

**Comment by avvertix** [comment]
Could you check if the MacOS binary is executable?

You can do that by entering the binaries folder and try to run the MacOS version directly

**Comment by Fidelix** [comment]
This issue needs to be re-opened.

I tried it on Linux and the same issue is there.

This needs to either be documented or the binaries need to be made executable

**Comment by avvertix** [comment]
We are open to accept pull requests on the topic
