### ISSUE TITLE
Error in PATCH request to tus server

### ISSUE THREAD

**Issue by shellprog** [OneOffTech/laravel-tus-upload#5]
Hi,
I tried to uplod files to tus server but it is responding with 500 error on patch request and response says

    Lockfile created, but doesn't exist

This is the request flow in my network tab
    
![capture](https://user-images.githubusercontent.com/3014913/39578515-65fabc32-4ef5-11e8-8ca0-37b8f8afffcc.PNG)

This is the output from artisan command

![capture2](https://user-images.githubusercontent.com/3014913/39578607-a627703e-4ef5-11e8-9285-41884424dd2c.PNG)

Did you faced same situation like this ? 

Help is appreciated.

**Comment by avvertix** [comment]
You can try running `tus:start --no-hooks`, so hooks will be disabled and the tus server will authorize all uploads. If the problem persists, then the routing/handling of the patch request needs to be verified. 

Currently the package is fully tested only on Linux systems. The implementation uses [shell scripts](https://github.com/OneOffTech/laravel-tus-upload/tree/master/hooks/linux) to execute hooks. I've succesfully run it on the [Windows Subsystem for Linux](https://github.com/OneOffTech/laravel-tus-upload#can-be-run-on-windows)

**Comment by shellprog** [comment]
I tried with --no-hooks with no luck.

I am on windows but i am using homestead for projects so it is a Linux environment in which scripts are executing. If i find any fix i will update it here.

**Comment by avvertix** [comment]
Oh, interesting development setup, I never tried that way. Are you running it behind a proxy or the port is exposed outside the VM?

**Comment by avvertix** [comment]
@heliomx sorry to hear that, I currently don't have access to my development environment, but as soon as I can I will try to replicate your setup. Could you give me more hints on the Nginx configuration you are using?

**Comment by shellprog** [comment]
Port is exposed to the outside of VM, I have changed my setup to not use homestead(vagrant) and now it works without any issue. Due to limited time I was unable to check more of what would be an issue here, will update once I get back to it.

**Comment by heliomx** [comment]
Hi @avvertix , I've solved the problem. Nginx was using docker's internal hostname and the HTTP Location response header was invalid. So I had to rewrite the header to "localhost" using proxy_set_header nginx command. 
tus-js-client uses the location header to construct the request url for PATCH requests.
