### ISSUE TITLE
Dependies Error

### ISSUE THREAD

**Issue by MaxKuz67** [OneOffTech/laravel-tus-upload#65]
Help! 

Run `composer require oneofftech/laravel-tus-upload`

 Problem 1
    - Root composer.json requires oneofftech/laravel-tus-upload ^0.10.1 -> satisfiable by oneofftech/laravel-tus-upload[v0.10.1].
    - oneofftech/laravel-tus-upload v0.10.1 requires illuminate/auth 6.*|7.*|8.* -> found illuminate/auth[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**How to fix?**

**Comment by avvertix** [comment]
Hi @MaxKuz67 are you requiring it in a Laravel 9 project?

**Comment by MaxKuz67** [comment]
> Hi @MaxKuz67 are you requiring it in a Laravel 9 project?

Yes, Laravel 9

**Comment by avvertix** [comment]
Currently the package doesn't support Laravel 9. As you can see in [composer.json](https://github.com/OneOffTech/laravel-tus-upload/blob/master/composer.json#L9) we depend on Laravel 6, 7 or 8

**Comment by MaxKuz67** [comment]
It's very sad :C

**Comment by avvertix** [comment]
If you want you can submit a pull request to change the necessary files to support Laravel 9. I will be more than happy to review it and merge it

**Comment by MaxKuz67** [comment]
> If you want you can submit a pull request to change the necessary files to support Laravel 9. I will be more than happy to review it and merge it

But I don't know how :( I would be very grateful if you could find the time and make support for Laravel 9

**Comment by avvertix** [comment]
I'll try over the weekend

**Comment by MaxKuz67** [comment]
> I'll try over the weekend

Thank you very much

**Comment by avvertix** [comment]
I just tagged version [0.11.0](https://github.com/OneOffTech/laravel-tus-upload/releases/tag/v0.11.0) that ensure you can require the package in a Laravel 9 project. 

For your knowledge you can have a look in #66 to see what I had to change
